// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hu.attila.csanyi.mongo.pizza.domain;

import hu.attila.csanyi.mongo.pizza.domain.BaseDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BaseDataOnDemand_Roo_Configurable {
    
    declare @type: BaseDataOnDemand: @Configurable;
    
}
